import { useMemo } from "react";
import { motion } from "framer-motion";
import { Download, Mail, Phone, MapPin, Linkedin, Globe, FileText } from "lucide-react";

// =====================
// Web CV — Ahmed Oday
// Stack: React + Tailwind + Framer Motion + Lucide icons
// Notes:
// - كل النص عربي وباتجاه RTL
// - حدّث بيانات الاتصال والروابط بالأسفل
// - زر "تحميل PDF" يستخدم window.print()
// =====================

export default function AhmedOdayCV() {
  const profile = useMemo(
    () => ({
      name: "أحمد عدي",
      title: "خريج علوم حياة — فني مختبر سريري",
      location: "العراق / [المدينة]",
      phone: "+964 [رقمك]",
      email: "your.email@example.com",
      linkedin: "https://www.linkedin.com/in/your-profile",
      website: "https://your-portfolio.example.com",
      summary:
        "خريج علوم حياة شغوف بالعمل المخبري، ملتزم بمعايير الجودة، ومتمكن من التحاليل الروتينية والمتقدمة بما يشمل تحليل البول العام (GUE) وفق إرشادات JCCLS، الهيماتولوجي، والكيمياء السريرية. أبحث عن فرصة عملية لأوظّف مهاراتي وأسهم في تحسين رعاية المرضى.",
    }),
    []
  );

  const skills = [
    {
      heading: "تحليل البول (GUE) — JCCLS",
      points: [
        "الفحص الفيزيائي، الكيميائي، والمجهري لعينات البول.",
        "استخدام شرائط القياس وأجهزة الأتمتة مع ضبط جودة داخلي.",
        "تحضير الراسب المجهري وتقييم الخلايا، البلورات، والأسطوانات.",
      ],
    },
    {
      heading: "الهيماتولوجي",
      points: [
        "CBC بالأجهزة الأوتوماتيكية والتحقق اليدوي.",
        "تحضير لطاخة الدم والتلوين والتفريق العددي.",
      ],
    },
    {
      heading: "الكيمياء السريرية",
      points: [
        "تحليل السيرم والبلازما على أجهزة شبه/كاملة الأتمتة.",
        "معايرة الأجهزة والمحاليل وتتبع منحنيات الضبط.",
      ],
    },
    {
      heading: "ضبط الجودة والسلامة الحيوية",
      points: [
        "QC داخلي وخارجي، توثيق الانحرافات والإجراءات التصحيحية.",
        "التعامل الآمن مع العينات والنفايات الحيوية.",
      ],
    },
    {
      heading: "المهارات العامة",
      points: [
        "Microsoft Office / Google Workspace.",
        "التواصل والعمل ضمن فريق، وإدارة الوقت.",
      ],
    },
  ];

  const education = [
    {
      degree: "بكالوريوس علوم حياة",
      org: "[اسم الجامعة]",
      year: "[سنة التخرج]",
      details: "مشروع تخرج: [اكتب عنوان مشروعك إن وجد].",
    },
  ];

  const courses = [
    "إرشادات JCCLS لتحليل البول (Urinalysis).",
    "السلامة والجودة المخبرية (Quality & Safety).",
    "الإسعافات الأولية (BLS).",
  ];

  const languages = [
    { name: "العربية", level: "اللغة الأم" },
    { name: "الإنجليزية", level: "جيد جداً" },
  ];

  const variants = {
    fadeUp: {
      hidden: { opacity: 0, y: 16 },
      show: { opacity: 1, y: 0, transition: { duration: 0.5 } },
    },
  } as const;

  return (
    <div dir="rtl" className="min-h-screen bg-gradient-to-b from-slate-50 to-white text-slate-800">
      {/* Header / Hero */}
      <header className="sticky top-0 z-40 backdrop-blur supports-[backdrop-filter]:bg-white/60 bg-white/70 border-b border-slate-200">
        <div className="mx-auto max-w-5xl px-4 sm:px-6 py-3 flex items-center justify-between gap-3">
          <div className="flex items-center gap-3">
            <div className="size-10 rounded-2xl bg-slate-900 text-white grid place-items-center font-bold">أ</div>
            <div>
              <h1 className="text-xl font-semibold leading-tight">{profile.name}</h1>
              <p className="text-sm text-slate-600">{profile.title}</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={() => window.print()}
              className="inline-flex items-center gap-2 rounded-2xl px-4 py-2 text-sm font-medium border border-slate-300 hover:bg-slate-100 shadow-sm"
            >
              <Download className="size-4" /> تحميل PDF
            </button>
            <a
              href={`mailto:${profile.email}`}
              className="inline-flex items-center gap-2 rounded-2xl px-4 py-2 text-sm font-medium bg-slate-900 text-white hover:bg-slate-800 shadow"
            >
              <Mail className="size-4" /> تواصل
            </a>
          </div>
        </div>
      </header>

      {/* Main */}
      <main className="mx-auto max-w-5xl px-4 sm:px-6 py-8 print:py-0 print:max-w-none print:px-10">
        {/* Top Card */}
        <motion.section
          variants={variants.fadeUp}
          initial="hidden"
          animate="show"
          className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm print:shadow-none print:border-0"
        >
          <div className="grid lg:grid-cols-[1.2fr,0.8fr] gap-8">
            <div className="space-y-4">
              <h2 className="text-2xl font-bold">الملخص المهني</h2>
              <p className="leading-8 text-slate-700">{profile.summary}</p>
              {/* Contact pills */}
              <ul className="mt-4 flex flex-wrap gap-2 text-sm">
                <li className="inline-flex items-center gap-2 rounded-full border border-slate-200 px-3 py-1.5">
                  <Phone className="size-4" /> {profile.phone}
                </li>
                <li className="inline-flex items-center gap-2 rounded-full border border-slate-200 px-3 py-1.5">
                  <Mail className="size-4" /> {profile.email}
                </li>
                <li className="inline-flex items-center gap-2 rounded-full border border-slate-200 px-3 py-1.5">
                  <MapPin className="size-4" /> {profile.location}
                </li>
                <li className="inline-flex items-center gap-2 rounded-full border border-slate-200 px-3 py-1.5">
                  <Linkedin className="size-4" />
                  <a href={profile.linkedin} target="_blank" className="underline decoration-dotted underline-offset-4">LinkedIn</a>
                </li>
                <li className="inline-flex items-center gap-2 rounded-full border border-slate-200 px-3 py-1.5">
                  <Globe className="size-4" />
                  <a href={profile.website} target="_blank" className="underline decoration-dotted underline-offset-4">Website</a>
                </li>
              </ul>
            </div>

            {/* Quick Highlights */}
            <div className="grid sm:grid-cols-2 lg:grid-cols-1 gap-3">
              <div className="rounded-2xl border border-slate-200 p-4 bg-slate-50">
                <p className="text-sm text-slate-600 mb-1">المجال</p>
                <p className="font-semibold">تحاليل طبية / مختبر سريري</p>
              </div>
              <div className="rounded-2xl border border-slate-200 p-4 bg-slate-50">
                <p className="text-sm text-slate-600 mb-1">جاهزية</p>
                <p className="font-semibold">متاح للدوام الفوري والتدريب</p>
              </div>
              <div className="rounded-2xl border border-slate-200 p-4 bg-slate-50">
                <p className="text-sm text-slate-600 mb-1">هدف مهني</p>
                <p className="font-semibold">تطوير خبرتي بالمختبر والمساهمة بجودة النتائج</p>
              </div>
            </div>
          </div>
        </motion.section>

        {/* Skills & Education */}
        <div className="mt-8 grid lg:grid-cols-2 gap-8">
          <motion.section
            variants={variants.fadeUp}
            initial="hidden"
            whileInView="show"
            viewport={{ once: true, margin: "-50px" }}
            className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"
          >
            <h2 className="text-2xl font-bold mb-4">المهارات المخبرية</h2>
            <div className="space-y-5">
              {skills.map((s, idx) => (
                <div key={idx} className="rounded-2xl border border-slate-200 p-4">
                  <h3 className="font-semibold mb-2">{s.heading}</h3>
                  <ul className="list-disc pr-6 space-y-1 marker:text-slate-400">
                    {s.points.map((p, i) => (
                      <li key={i} className="leading-7">{p}</li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>
          </motion.section>

          <motion.section
            variants={variants.fadeUp}
            initial="hidden"
            whileInView="show"
            viewport={{ once: true, margin: "-50px" }}
            className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"
          >
            <h2 className="text-2xl font-bold mb-4">التعليم</h2>
            <div className="space-y-4">
              {education.map((e, idx) => (
                <div key={idx} className="rounded-2xl border border-slate-200 p-4 bg-slate-50">
                  <p className="font-semibold">{e.degree}</p>
                  <p className="text-sm text-slate-600">{e.org} — {e.year}</p>
                  <p className="text-sm mt-2">{e.details}</p>
                </div>
              ))}
            </div>

            <h2 className="text-2xl font-bold mt-6 mb-3">الدورات والشهادات</h2>
            <ul className="space-y-2">
              {courses.map((c, idx) => (
                <li key={idx} className="inline-flex items-start gap-2 rounded-xl border border-slate-200 px-3 py-2 bg-white">
                  <FileText className="size-4 mt-1 shrink-0" />
                  <span className="leading-7">{c}</span>
                </li>
              ))}
            </ul>

            <h2 className="text-2xl font-bold mt-6 mb-3">اللغات</h2>
            <ul className="flex flex-wrap gap-2">
              {languages.map((l, idx) => (
                <li key={idx} className="rounded-full border border-slate-200 px-4 py-1.5 bg-slate-50 text-sm">
                  {l.name}: {l.level}
                </li>
              ))}
            </ul>
          </motion.section>
        </div>

        {/* Footer note */}
        <footer className="mt-10 mb-6 text-center text-sm text-slate-500">
          © {new Date().getFullYear()} {profile.name}. هذا السيرة الذاتية الإلكترونية صُمّمت باستخدام React + Tailwind.
        </footer>
      </main>

      {/* Print styles */}
      <style>{`
        @media print {
          header { display: none; }
          main { padding: 0 !important; }
          a { text-decoration: none !important; }
          .shadow, .shadow-sm, .shadow-md, .shadow-lg { box-shadow: none !important; }
          .bg-slate-50 { background: white !important; }
          .border-slate-200 { border-color: #e5e7eb !important; }
        }
      `}</style>
    </div>
  );
}
